### ISSUE TITLE
No need to access Users Collection in mongodb

### ISSUE THREAD

**Issue by oleksbard** [ivanoff/gl#2]
In next code you are accessing the Users Collection: 

``` js
db.connect( URL, function( err ) {
    if ( err ) {
        console.log( 'Unable to connect to Mongo' );
        process.exit( 1 );
    } else {
        db.collection = db.get().collection( COLLECTION ); // <---
        app.listen( PORT, function() {
            console.log( 'Listening on port ' + PORT + '...' )
        })
    }
})
```

This isn't needed. Do you use it for something special ?

**Comment by ivanoff** [comment]
Need I put select of collection to modules/db.js ?

**Comment by oleksbard** [comment]
Basically, your model is a collection. In case of this application you need only one collection. But try to think about the application that is needed more than 1 collection. What architecture you will implement to use several collections in the same moment ?
